################################################################
# create_project.tcl
# Vivado project creation script for EBAZ4205 NES (tarunes port)
#
# Usage:
#   vivado -mode batch -source create_project.tcl
#   or from Vivado Tcl console:
#   source create_project.tcl
#
# Requirements:
#   - Vivado 2023.2 or later
#   - Run from the project/ directory
################################################################

set project_name "ebaz4205_nes"
set project_dir  [file normalize "./vivado"]
set origin_dir   [file normalize "."]

# Create project
create_project $project_name $project_dir -part xc7z010clg400-1 -force

# Set project properties
set_property board_part "" [current_project]
set_property target_language Verilog [current_project]
set_property simulator_language Mixed [current_project]

################################################################
# Add RTL source files
################################################################

# tarunes SystemVerilog sources (generated by Veryl)
set sv_files [glob -nocomplain $origin_dir/rtl/tarunes_sv/*.sv]
add_files -norecurse $sv_files
set_property file_type SystemVerilog [get_files $sv_files]

# EBAZ4205-specific RTL (Verilog)
set v_files [list \
    $origin_dir/rtl/ebaz4205_nes_top.v \
    $origin_dir/rtl/nes_button_map.v \
    $origin_dir/rtl/button_debounce.v \
    $origin_dir/rtl/bram_tdp_32kx8.v \
    $origin_dir/rtl/bram_tdp_8kx8.v \
]
add_files -norecurse $v_files

# Modified NES top module (SystemVerilog)
add_files -norecurse $origin_dir/rtl/nes_top_ebaz4205.sv
set_property file_type SystemVerilog [get_files $origin_dir/rtl/nes_top_ebaz4205.sv]

# rgb2dvi VHDL sources
set vhd_files [glob -nocomplain $origin_dir/rtl/rgb2dvi/*.vhd]
add_files -norecurse $vhd_files
set_property file_type VHDL [get_files $vhd_files]

# Set top module
set_property top ebaz4205_nes_top [current_fileset]

################################################################
# Add constraints
################################################################
add_files -fileset constrs_1 -norecurse $origin_dir/vivado/constraints/ebaz4205_nes.xdc

################################################################
# Create Block Design for PS configuration
################################################################
source $origin_dir/vivado/create_bd.tcl

################################################################
# Synthesis settings
################################################################
set_property strategy Flow_PerfOptimized_high [get_runs synth_1]
set_property STEPS.SYNTH_DESIGN.ARGS.DIRECTIVE PerformanceOptimized [get_runs synth_1]
set_property STEPS.SYNTH_DESIGN.ARGS.FLATTEN_HIERARCHY rebuilt [get_runs synth_1]

# Implementation settings
set_property strategy Performance_ExplorePostRoutePhysOpt [get_runs impl_1]
set_property STEPS.PHYS_OPT_DESIGN.IS_ENABLED true [get_runs impl_1]
set_property STEPS.POST_ROUTE_PHYS_OPT_DESIGN.IS_ENABLED true [get_runs impl_1]

puts "Project created successfully: $project_dir/$project_name.xpr"
puts ""
puts "Next steps:"
puts "  1. Open project: open_project $project_dir/$project_name.xpr"
puts "  2. Run synthesis: launch_runs synth_1 -jobs 4"
puts "  3. Run implementation: launch_runs impl_1 -to_step write_bitstream -jobs 4"
